package engine

import (
	"bytes"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"text/template"

	"github.com/Salv4d/derrick/internal/config"
	"github.com/Salv4d/derrick/internal/ui"
)

const nixFlakeTemplate = `
{
	description = "Derrick Auto-Generated Flake";

	inputs = {
		nixpkgs.url = "{{ .Registry }}";{{ range $regName, $regUrl := .ExtraRegistries }}
		{{ $regName }}.url = "{{ $regUrl }}";{{ end }}
	};

	outputs = { self, nixpkgs{{ range $name, $url := .ExtraRegistries }}, {{ $name }}{{ end }}, ... }:
	let
		system = "x86_64-linux";
		pkgs = nixpkgs.legacyPackages.${system};{{ range $name, $url := .ExtraRegistries }}
		{{ $name }}_pkgs = {{ $name }}.legacyPackages.${system};{{ end }}
	in
	{
		devShells.${system}.default = pkgs.mkShell {
			packages = [
			{{ range .Packages }}
			{{ . }}
			{{ end }}
			];
		};
	};
}
`

// NixTemplateData holds data for rendering the Nix flake template.
type NixTemplateData struct {
	Registry        string
	Packages        []string
	ExtraRegistries map[string]string
}

// BootEnvironment initializes and validates the Nix sandbox.
func BootEnvironment(configPath string, requestPackages []config.NixPackage, registryURL string, outDir string) error {
	ui.Section("Derrick Sandbox Initialization")

	err := EnsureNixEnvironment(configPath, requestPackages, registryURL, outDir)
	if err != nil {
		return err
	}

	_, err = ValidateAndResolve(configPath, requestPackages, registryURL, outDir)
	if err != nil {
		return err
	}

	ui.Success("Environment verified and locked. Ready for execution.")
	return nil
}

// EnsureNixEnvironment creates the flake.nix and ensures isolation.
func EnsureNixEnvironment(configPath string, packages []config.NixPackage, customRegistry string, outDir string) error {
	if len(packages) == 0 {
		return nil
	}

	ui.Task("Ensuring Nix environment isolation")

	registry := customRegistry
	if registry == "" {
		registry = config.DefaultNixRegistry
	}

	dir := outDir
	if dir == "" {
		dir = ".derrick"
	}
	err := os.MkdirAll(dir, 0o755)
	if err != nil {
		ui.Error("FAILED")
		return fmt.Errorf("failed to create %s directory: %w", dir, err)
	}

	tmpl, err := template.New("flake").Parse(nixFlakeTemplate)
	if err != nil {
		ui.Error("FAILED")
		return fmt.Errorf("failed to parse Nix template: %w", err)
	}

	data := NixTemplateData{
		Registry:        registry,
		ExtraRegistries: make(map[string]string),
	}

	registryIndex := 1
	registryMap := make(map[string]string)

	for _, p := range packages {
		targetPkg := ""
		if p.Registry != "" && p.Registry != registry {
			regName, exists := registryMap[p.Registry]
			if !exists {
				regName = fmt.Sprintf("reg%d", registryIndex)
				registryIndex++
				registryMap[p.Registry] = regName
				data.ExtraRegistries[regName] = p.Registry
			}
			targetPkg = fmt.Sprintf("%s_pkgs.%s", regName, p.Name)
		} else {
			targetPkg = fmt.Sprintf("pkgs.%s", p.Name)
		}
		data.Packages = append(data.Packages, targetPkg)
	}

	var flakeContent bytes.Buffer
	err = tmpl.Execute(&flakeContent, data)
	if err != nil {
		ui.Error("FAILED")
		return fmt.Errorf("failed to execute Nix template: %w", err)
	}

	flakePath := filepath.Join(dir, "flake.nix")
	err = os.WriteFile(flakePath, flakeContent.Bytes(), 0o644)
	if err != nil {
		ui.Error("FAILED")
		return fmt.Errorf("failed to write flake.nix: %w", err)
	}

	ui.Success("DONE")
	return nil
}

// NixEnv returns the current environment with NIXPKGS_ALLOW_UNFREE=1 set,
// so that all Nix invocations can resolve unfree packages (e.g. Cursor, VSCode).
func NixEnv() []string {
	return append(os.Environ(), "NIXPKGS_ALLOW_UNFREE=1")
}

// WrapWithNix returns a command array to run inside the Nix environment.
func WrapWithNix(command string, outDir string) []string {
	if outDir == "" {
		outDir = ".derrick"
	}
	absPath, _ := filepath.Abs(outDir)
	return []string{
		"nix",
		"develop",
		"--impure",
		fmt.Sprintf("path:%s#default", absPath),
		"-c",
		"bash",
		"-c",
		command,
	}
}

// IsNixInstalled checks if the nix binary is available in PATH.
func IsNixInstalled() bool {
	_, err := exec.LookPath("nix")
	return err == nil
}

// WriteEnvRC writes a direnv .envrc in projectDir that activates the Nix
// flake generated by derrick. It is a no-op if .envrc already exists.
// Returns true if the file was newly created.
func WriteEnvRC(projectDir string) (bool, error) {
	path := filepath.Join(projectDir, ".envrc")
	if _, err := os.Stat(path); err == nil {
		return false, nil
	}
	const content = "# Generated by derrick — requires nix-direnv (https://github.com/nix-community/nix-direnv)\nuse flake ./.derrick#default\n"
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return false, fmt.Errorf("failed to write .envrc: %w", err)
	}
	return true, nil
}
