package engine

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"

	"github.com/Salv4d/derrick/internal/config"
	"github.com/Salv4d/derrick/internal/ui"
)

// NixProvider implements Provider using Nix flake dev shells.
type NixProvider struct{}

func (n *NixProvider) Name() string { return "nix" }

// IsAvailable checks that the nix binary is reachable.
func (n *NixProvider) IsAvailable() error {
	if !IsNixInstalled() {
		return &DerrickError{
			Message: "Nix is not installed on this system.",
			Fix:     `curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install`,
		}
	}
	return nil
}

// Provision writes .derrick/flake.nix, resolves the registry, and drops a
// .envrc for direnv users. After this returns, `nix develop` from the project
// root has a cached resolved environment — safe to use from setup hooks.
func (n *NixProvider) Provision(cfg *config.ProjectConfig) error {
	if len(cfg.Nix.Packages) == 0 {
		return fmt.Errorf("no nix.packages specified in derrick.yaml")
	}

	registry := cfg.Nix.Registry
	if registry == "" {
		registry = config.DefaultNixRegistry
	}

	ui.Taskf("Resolving %d Nix packages", len(cfg.Nix.Packages))
	if err := BootEnvironment("derrick.yaml", cfg.Nix.Packages, registry, ""); err != nil {
		return err
	}

	cwd, err := os.Getwd()
	if err != nil {
		return fmt.Errorf("could not determine project directory: %w", err)
	}
	created, err := WriteEnvRC(cwd)
	if err != nil {
		ui.Warningf("direnv: %v", err)
	} else if created {
		ui.Infof("Created .envrc — run 'direnv allow' to activate automatic environment loading")
	}
	return nil
}

// Start is a no-op for Nix: there are no long-running services to boot. Every
// `nix develop` invocation (hooks, shell) enters a fresh process-scoped dev
// shell from the flake Provision already resolved.
func (n *NixProvider) Start(_ *config.ProjectConfig, _ Flags) error { return nil }

// Stop is a no-op for Nix: the dev shell exits when the process ends.
func (n *NixProvider) Stop(_ *config.ProjectConfig) error { return nil }

// Shell opens an interactive Nix dev shell, or runs a single command when
// args is non-empty.
func (n *NixProvider) Shell(cfg *config.ProjectConfig, args []string) error {
	eng := NewShellEngine()
	return eng.EnterSandbox(".derrick", args)
}

// Status reports whether this project's Nix environment is materialized.
// Running is true only when the flake generated by `derrick start` exists
// on disk — the mere presence of a `nix` binary on the host is not enough
// to conclude the project is ready.
func (n *NixProvider) Status(cfg *config.ProjectConfig) (EnvironmentStatus, error) {
	if _, err := exec.LookPath("nix"); err != nil {
		return EnvironmentStatus{Running: false, Details: "nix not installed"}, nil
	}
	if _, err := os.Stat(filepath.Join(".derrick", "flake.nix")); err != nil {
		return EnvironmentStatus{Running: false, Details: "flake not built — run 'derrick start'"}, nil
	}
	return EnvironmentStatus{Running: true, Details: "flake available at .derrick/flake.nix"}, nil
}
