theme: jekyll-theme-minimal
title: Derrick CLI
description: A smart control plane uniting absolute reproducibility of Nix with the containerization of Docker Compose.
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - .cursorrules
